# Generated by Django 4.1 on 2024-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAuthentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="portfolio",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
